components/PageUrlRule.php
=> Fixed syntax error in PageUrlRule.php

views/view/iframe.php
This is a fix for issue #59 and makes webpages more responsive for iframe.
=> Fix: Responsive iFrame

views/container/iframe.php
Forgot to add this into #60 which will make iframe more responsive.
=> Fix: Responsive iFrame 2

views/common/list.php
1. Create a Link URL with title `<script>alert(document.cookie);</script>`
2. Save
3. Go to `/custom_pages/container/list`
4. XSS
=> Fix XSS on list view

migrations/m160907_175706_default_templates.php, migrations/m170413_085114_download_link_template.php, migrations/m190213_135905_blank_template.php
Issue: https://github.com/humhub/humhub/issues/4428
=> Replace db Expression time now with func date()

components/PhpPageContainer.php, docs/CHANGELOG.md, module.json
Issue https://github.com/humhub/humhub-modules-custom-pages/issues/151
=> Check old dir with custom php files

Events.php, Module.php, config.php, controllers/AbstractCustomContainerController.php, controllers/PageController.php, docs/CHANGELOG.md, models/CustomContentContainer.php, module.json, modules/template/models/PagePermission.php, permissions/ManagePages.php, widgets/AdminMenu.php
Implement new group permission "Can manage custom pages" for request from issue https://github.com/humhub/humhub-modules-custom-pages/issues/57#issuecomment-734862269
=> New group permission “Can manage custom pages”

models/CustomContentContainer.php, models/Page.php
Quick fix for already merged PR https://github.com/humhub/humhub-modules-custom-pages/pull/157#issuecomment-744412245
=> Fix snippet creating

docs/CHANGELOG.md, module.json, modules/template/widgets/PageConfigurationButton.php, modules/template/widgets/views/pageConfigurationButton.php, views/container/markdown.php, views/global/markdown.php
Issue: https://github.com/humhub/humhub-modules-custom-pages/issues/168
=> Add edit button to markdown pages

docs/CHANGELOG.md, views/global/markdown.php
Issue: https://github.com/humhub/custom-pages/issues/185
=> Fix markdown page width on mobile/small screens

docs/CHANGELOG.md, module.json, views/common/edit.php
Issue: https://github.com/humhub/custom-pages/issues/187
=> Fix lost visibility options for snippets

Events.php, config.php, docs/CHANGELOG.md, models/Page.php
Issue: https://github.com/humhub/custom-pages/issues/196
=> Footer menu pages

docs/CHANGELOG.md, module.json, modules/template/assets/SourceEditorAsset.php, modules/template/views/admin/editSource.php
Issue: https://github.com/humhub/custom-pages/issues/211
=> Fix duplicated template HTML source field

docs/CHANGELOG.md, module.json, widgets/TinyMce.php
Issue: https://github.com/humhub/custom-pages/issues/220
=> Allow script tags in TinyMCE editor

Events.php, config.php, docs/CHANGELOG.md, models/Page.php, tests/codeception/acceptance/CreateGlobalPageCest.php
https://github.com/humhub/custom-pages/issues/218
=> Allow custom pages for "People" page

docs/CHANGELOG.md, lib/templates/twig/DatabaseTwigLoader.php, lib/templates/twig/TwigEngine.php, module.json, modules/template/models/AssetVariable.php
Issue: https://github.com/humhub/custom-pages/issues/232
=> Migrate to Twig 3 and compatible with PHP 8.1

controllers/PageController.php, docs/CHANGELOG.md, models/CustomContentContainer.php, models/Target.php, module.json, widgets/views/targetPageList.php
Issue: https://github.com/humhub/custom-pages/issues/238
=> Allow HTML Pages and Snippets only for global admins

docs/CHANGELOG.md, models/CustomContentContainer.php, models/Target.php, models/forms/AddPageForm.php, module.json
Issue: https://github.com/humhub/custom-pages/issues/241
=> Fix access to view HTML pages

modules/template/models/AssetVariable.php
Issue: https://github.com/humhub/custom-pages/issues/247
=> Fix TypeError while opening Inline Editor

docs/CHANGELOG.md, models/CustomContentContainer.php, module.json, modules/template/models/AssetVariable.php
Issue: https://github.com/humhub/custom-pages/issues/251
=> Fix view page from template allowed in Space

Events.php, docs/CHANGELOG.md
This doesn't completely make everything translatable just makes the title comply with [Translation Overwrites](https://docs.humhub.org/docs/admin/translations/#overwrite-translation-messages).
Requested: https://community.humhub.com/content/perma?id=263004
=> Enh: Translatable Titles

docs/CHANGELOG.md, module.json, modules/template/models/AssetVariable.php
Issue: https://github.com/humhub/custom-pages/issues/254
=> Fix compatible with PHP 8.1

docs/CHANGELOG.md, module.json, modules/template/controllers/AdminController.php, modules/template/controllers/OwnerContentController.php
Issue: https://github.com/humhub/custom-pages/issues/256
=> Fix richtext on template editor

modules/template/controllers/OwnerContentController.php, modules/template/models/HumHubRichtextContent.php, modules/template/models/RichtextContent.php, modules/template/models/forms/ContentFormItem.php, modules/template/models/forms/EditMultipleElementsForm.php, widgets/TinyMce.php
Related to issue: https://github.com/humhub/custom-pages/issues/259
=> Fix tinymce editor initialization after it was loaded on modal window

docs/CHANGELOG.md, module.json, widgets/TinyMce.php
Issue: https://github.com/humhub/custom-pages/issues/261
=> Add list buttons in toolbar of RichText TinyMCE editor

Events.php, components/PageUrlRule.php, docs/CHANGELOG.md
https://github.com/humhub/custom-pages/issues/263
=> Conflicts if a page in a content container has the same ID as a global page

Events.php, controllers/PageController.php, helpers/Url.php, interfaces/CustomPagesService.php, module.json, modules/template/models/AssetVariable.php, views/common/edit.php, widgets/views/targetPageList.php
Issue: https://github.com/humhub/humhub-internal/issues/12
=> Fix page deletion

widgets/views/addContentTypeRow.php
Issue: https://github.com/humhub/custom-pages/issues/268
=> Don't wrap page type

docs/CHANGELOG.md, module.json, modules/template/models/Template.php, modules/template/views/admin/editUsage.php
Issue: https://github.com/humhub/custom-pages/issues/277#issuecomment-1552977546
=> Template usage: display content container and state

docs/CHANGELOG.md, models/HtmlType.php
Issue: https://github.com/humhub/custom-pages/issues/284
=> Hide files of HTML pages in stream wall entry

models/CustomContentContainer.php
Issue: https://github.com/humhub/custom-pages/issues/288
=> Add missing translations

Events.php, docs/CHANGELOG.md
Issue: https://github.com/humhub/custom-pages/issues/291
=> Fix broken URL in email footer

Module.php, docs/CHANGELOG.md
Issue: https://github.com/humhub/humhub/issues/6486#issuecomment-1681848783
=> Initialize module content class

controllers/PageController.php, controllers/ViewController.php, docs/CHANGELOG.md, module.json
https://github.com/humhub/humhub-internal/issues/113
=> Fix visibility of the method `Controller::getAccessRules()`

controllers/ViewController.php, docs/CHANGELOG.md, helpers/Html.php, lib/templates/twig/TwigEngine.php, models/Page.php, modules/template/components/TemplateRenderer.php
Issue: https://github.com/humhub/custom-pages/issues/305
=> JavaScript nonce placeholder for templates & HTML pages

Events.php, docs/CHANGELOG.md
fixes https://github.com/humhub/custom-pages/issues/319 (which should be transferred to this repo)
=> Fix active tab in Admin Menu

docs/CHANGELOG.md, models/CustomContentContainer.php, models/IframeType.php, module.json
https://github.com/humhub/humhub-internal/issues/267#issuecomment-2163119311
=> Fix saving of iframe URL by space admin

docs/CHANGELOG.md, models/CustomContentContainer.php, models/PageType.php, module.json
https://github.com/humhub/wording/issues/159#issuecomment-2225134700
=> Renaming page and snippet to global and space types

docs/CHANGELOG.md, models/Page.php, modules/template/components/TemplateRenderer.php
https://github.com/humhub/humhub-internal/issues/310
=> Ignore cache on content search index building

docs/CHANGELOG.md, models/CustomContentContainer.php, models/MarkdownType.php, models/TemplateType.php, module.json, modules/template/models/ContainerContent.php, modules/template/models/ContainerContentDefinition.php
https://github.com/humhub/custom-pages/issues/347
=> Fix errors after save a new page

docs/CHANGELOG.md, module.json, views/container/markdown.php, views/global/markdown.php, widgets/views/wallEntry.php
https://github.com/humhub/humhub-internal/issues/409#issuecomment-2395175788
=> defer markdown rendering

Module.php, docs/CHANGELOG.md, migrations/m241023_070403_rss_content.php, modules/template/controllers/AdminController.php, modules/template/models/OwnerContent.php, modules/template/models/OwnerContentVariable.php, modules/template/models/RssContent.php, modules/template/models/TemplateContentIterable.php, modules/template/widgets/views/rssContentFormFields.php
https://github.com/humhub/custom-pages-internal/issues/17
=> Template - Add RSS Element Type

docs/CHANGELOG.md, modules/template/models/TemplateContentActiveRecord.php
https://github.com/humhub/custom-pages/issues/355
=> Fix visibility of attached images to Template Layout

docs/CHANGELOG.md, migrations/m241203_100135_records_content.php, modules/template/controllers/AdminController.php, modules/template/models/RecordsContent.php, modules/template/models/SpacesContent.php, modules/template/models/UsersContent.php, modules/template/widgets/views/recordsContentFormFields.php, modules/template/widgets/views/spacesContentFormFields.php, modules/template/widgets/views/usersContentFormFields.php
https://github.com/humhub/custom-pages-internal/issues/26
=> Template - Spaces and Users Element Type

Module.php, docs/CHANGELOG.md, lib/templates/twig/SecurityPolicy.php, lib/templates/twig/TwigEngine.php
https://github.com/humhub/custom-pages-internal/issues/30
=> Fix allowed properties for Twig v3.14.1+

modules/template/models/RssContent.php
https://github.com/humhub/humhub-internal/issues/487
=> Template - RSS Element: Parse items with attributes

modules/template/models/RecordsContent.php, modules/template/models/SpacesContent.php, modules/template/models/UsersContent.php, modules/template/widgets/views/spacesContentFormFields.php, modules/template/widgets/views/usersContentFormFields.php
https://github.com/humhub/humhub-internal/issues/488#issuecomment-2557660221
=> Allow current user for elements "Spaces" and "Users"

modules/template/models/RssContent.php
https://github.com/humhub/humhub-internal/issues/487#issuecomment-2557420680
=> Parse image URL from RSS item

docs/CHANGELOG.md, migrations/m250116_153924_container_templates.php, modules/template/elements/ContainerDefinition.php, modules/template/models/Template.php, modules/template/widgets/views/elements/container.php
https://github.com/humhub/custom-pages-internal/issues/35
=> Use template name for allowed templates in the container element dynamic attributes

Module.php
https://github.com/humhub/custom-pages-internal/issues/32#issuecomment-2611036302
=> Add twig filter "striptags"

modules/template/models/forms/EditItemForm.php, modules/template/widgets/views/editItemModal.php
https://github.com/humhub/custom-pages-internal/issues/37
=> Hide container item title on edit form

modules/template/controllers/ElementContentController.php, modules/template/elements/BaseContentContainerElement.php, modules/template/elements/BaseRecordsElement.php, modules/template/widgets/views/editElementModal.php
https://github.com/humhub/custom-pages-internal/issues/39
=> Hide field "Label" on edit element content

modules/template/elements/BaseElementContent.php, modules/template/models/TemplateElement.php, modules/template/resources/js/humhub.custom_pages.template.TemplateElement.js, modules/template/resources/js/humhub.custom_pages.template.editor.js, resources/css/custom-pages.css
https://github.com/humhub/custom-pages-internal/issues/44
=> Improve UI hover behavior on container inline editing

docs/CHANGELOG.md, module.json, modules/template/models/ContainerContentItem.php
https://github.com/humhub/custom-pages-internal/issues/38
=> Fix image view permission from sub container

controllers/AbstractCustomContainerController.php, controllers/ViewController.php, docs/CHANGELOG.md, helpers/Url.php, modules/template/assets/InlineEditorAsset.php, modules/template/elements/BaseElementContent.php, modules/template/elements/BaseElementVariable.php, modules/template/elements/ContainerElement.php, modules/template/elements/ContainerItem.php, modules/template/elements/TextElement.php, modules/template/models/Template.php, modules/template/models/TemplateInstance.php, modules/template/resources/css/template-pages.css, modules/template/resources/js/humhub.custom_pages.template.TemplateStructure.js, modules/template/resources/js/humhub.custom_pages.template.editor.js, modules/template/services/TemplateInstanceRendererService.php, modules/template/widgets/TemplatePage.php, modules/template/widgets/TemplatePageEditButton.php, modules/template/widgets/TemplateStructure.php, modules/template/widgets/views/templatePageEditButton.php, modules/template/widgets/views/templateStructure.php, tests/codeception/unit/template/TemplateContentTest.php, tests/codeception/unit/template/TemplateElementTest.php, types/TemplateType.php, views/container/edit_snippet.php, views/container/template.php, views/global/edit_snippet.php, views/global/template.php, widgets/views/snippet_template.php
https://github.com/humhub/custom-pages-internal/issues/6
=> Structure overview

docs/CHANGELOG.md, modules/template/controllers/AdminController.php, modules/template/models/Template.php, modules/template/views/admin/edit.php, modules/template/views/admin/index.php
https://github.com/humhub/custom-pages-internal/issues/7
=> Copy templates

Module.php, docs/CHANGELOG.md, lib/templates/twig/MarkdownExtension.php, lib/templates/twig/TwigEngine.php
https://github.com/humhub/custom-pages-internal/issues/63
=> Twig extension to process markdown text

docs/CHANGELOG.md, module.json, modules/template/widgets/views/templateStructure.php
https://github.com/humhub/custom-pages-internal/issues/72
=> Display "Edit template" menu on structure view

docs/CHANGELOG.md, models/CustomPage.php
https://github.com/humhub/custom-pages-internal/issues/70
=> Allow templates with option "Allow in spaces" also for global pages

docs/CHANGELOG.md, models/CustomPage.php, views/common/edit.php
https://github.com/humhub/custom-pages-internal/issues/78
=> Allow to change category of custom page

docs/CHANGELOG.md, module.json, modules/template/elements/ImageElementVariable.php
https://github.com/humhub/custom-pages-internal/issues/83
=> Fix image element variable properties

docs/CHANGELOG.md, modules/template/elements/BaseContentRecordElement.php, modules/template/elements/BaseContentRecordsElement.php, modules/template/elements/PostElement.php
https://github.com/humhub/custom-pages-internal/issues/87
=> Use content ID for Content Record Elements

Module.php, docs/CHANGELOG.md, lib/templates/twig/TwigEngine.php, lib/templates/twig/YiiFormaterExtension.php, module.json
https://github.com/humhub/custom-pages-internal/issues/88
=> Add Yii formatter for Twig filters

docs/CHANGELOG.md, helpers/Url.php, modules/template/assets/TemplatePageStyleAsset.php, modules/template/resources/css/template-pages.css, modules/template/widgets/TemplatePageEditButton.php, modules/template/widgets/views/templatePageEditButton.php, modules/template/widgets/views/templateStructure.php
https://github.com/humhub/custom-pages-internal/issues/92
=> Add context menu to Structure View

migrations/m241111_164223_refactor.php
https://github.com/humhub/custom-pages/issues/436#issuecomment-3068375025
=> Store old page/snippet IDs

Module.php, docs/CHANGELOG.md, docs/MANUAL-TEMPLATE.md, migrations/m250422_145411_default_template.php, modules/template/elements/BaseContentRecordElementVariable.php, modules/template/elements/ContainerElementVariable.php, modules/template/resources/css/template-pages.css
https://github.com/humhub/custom-pages-internal/issues/94
=> Render container edit wrapper attributes separately

docs/CHANGELOG.md, helpers/Url.php, interfaces/CustomPagesService.php, models/CustomPage.php, module.json, modules/template/elements/UserElement.php, modules/template/models/Template.php, modules/template/services/TemplateInstanceDuplicatorService.php
https://github.com/humhub/custom-pages-internal/issues/99
=> Fix depreciation warnings on PHP 8.4

Events.php, docs/CHANGELOG.md, helpers/PageType.php, interfaces/CustomPagesService.php, widgets/views/targetPageList.php
https://github.com/humhub/custom-pages-internal/issues/77
=> New category "Start Page"

Events.php, controllers/AbstractCustomContainerController.php, controllers/ViewController.php, docs/CHANGELOG.md, models/CustomPage.php, module.json, modules/template/components/TemplateAccessFilter.php, modules/template/controllers/ElementContentController.php, modules/template/helpers/PagePermissionHelper.php, modules/template/widgets/TemplatePageEditButton.php, modules/template/widgets/views/templatePageEditButton.php, views/container/template.php, views/global/template.php, widgets/SnippetWidget.php
https://github.com/humhub/custom-pages-internal/issues/106
=> Fix edit template page by space admin

docs/CHANGELOG.md, modules/template/widgets/TemplateStructure.php
https://github.com/humhub/custom-pages/issues/457
=> Fix adding items to empty container

docs/CHANGELOG.md, docs/MANUAL-TEMPLATE.md, module.json, modules/template/elements/FileElementVariable.php, modules/template/elements/ImageElementVariable.php
https://github.com/humhub/news/pull/113#issuecomment-3345774976
=> Add url property for file template element

docs/CHANGELOG.md, modules/template/elements/BaseContentRecordsElement.php
https://github.com/humhub/custom-pages-internal/issues/111
=> New filter "Exclude Space" for template content records list element
